### PR TITLE
Add conditions on when to enter the recursion loop

### PR DESCRIPTION
**Pull request by aknarts**
I was getting an issue when if trying to get messages from 1:1 room with Max=1 I was getting random amount of messages back(82,72).

Turns out the pagination is not handling it well for 1:1 so added a little check to verify if we already got all we asked for.

There is probably a better way of doing this but this is quick and dirty hack to stop a road block for me.

### CODE REVIEW

**Comment by darrenparkinson** [comment]
I just realised that this is similar to the issue #3 I just posted.

**Comment by jbogarin** [comment]
Sorry for the delay guys, I've been away from this for a while. I'll definitively work on it this week. Thanks again for raising the issue.

**Comment by jbogarin** [comment]
Yeah, if I’m not mistaken, it’s the same as #3. @aknarts could you see our discussion there and give us your feedback?

**Comment by jbogarin** [comment]
@aknarts I had the same problem in all of the library, not only messages. I changed the logic a little bit and included a paginate option to indicate if you need more records or not.

**Pull request closed without merging**
